-- Esquema de negocio version 2.1.0. No contiene DROP, TRUNCATE ni PURGE.

CREATE TABLE TRANSACCIONES_PROCESADAS (
    ID NUMBER(19) PRIMARY KEY,
    FECHA DATE NOT NULL,
    MONTO NUMBER(15,2) NOT NULL,
    TIPO VARCHAR2(20) NOT NULL,
    ESTADO VARCHAR2(30) NOT NULL,
    OBSERVACION VARCHAR2(250)
);

CREATE TABLE RESUMEN_TRANSACCIONES_DIARIAS (
    FECHA DATE PRIMARY KEY,
    TOTAL_TRANSACCIONES NUMBER(10) DEFAULT 0 NOT NULL,
    TOTAL_CREDITOS NUMBER(10) DEFAULT 0 NOT NULL,
    TOTAL_DEBITOS NUMBER(10) DEFAULT 0 NOT NULL,
    TOTAL_ANOMALIAS NUMBER(10) DEFAULT 0 NOT NULL,
    MONTO_CREDITOS NUMBER(15,2) DEFAULT 0 NOT NULL,
    MONTO_DEBITOS NUMBER(15,2) DEFAULT 0 NOT NULL
);

CREATE TABLE INTERESES_CALCULADOS (
    CUENTA_ID NUMBER(19) PRIMARY KEY,
    NOMBRE VARCHAR2(150) NOT NULL,
    SALDO_INICIAL NUMBER(15,2) NOT NULL,
    EDAD NUMBER(3),
    TIPO VARCHAR2(30) NOT NULL,
    TASA_INTERES NUMBER(8,4),
    INTERES_CALCULADO NUMBER(15,2),
    SALDO_FINAL NUMBER(15,2),
    ESTADO VARCHAR2(30) NOT NULL,
    OBSERVACION VARCHAR2(250)
);

CREATE TABLE MOVIMIENTOS_ANUALES (
    SOURCE_KEY VARCHAR2(64) PRIMARY KEY,
    SOURCE_LINE NUMBER(10) NOT NULL,
    CUENTA_ID NUMBER(19) NOT NULL,
    FECHA DATE NOT NULL,
    TRANSACCION VARCHAR2(30) NOT NULL,
    MONTO NUMBER(15,2) NOT NULL,
    DESCRIPCION VARCHAR2(250),
    ESTADO VARCHAR2(30) NOT NULL,
    OBSERVACION VARCHAR2(250)
);

CREATE TABLE ESTADOS_CUENTA_ANUALES (
    CUENTA_ID NUMBER(19) PRIMARY KEY,
    TOTAL_INGRESOS NUMBER(15,2) DEFAULT 0 NOT NULL,
    TOTAL_EGRESOS NUMBER(15,2) DEFAULT 0 NOT NULL,
    SALDO_NETO NUMBER(15,2) DEFAULT 0 NOT NULL,
    CANTIDAD_MOVIMIENTOS NUMBER(10) DEFAULT 0 NOT NULL,
    CANTIDAD_ANOMALIAS NUMBER(10) DEFAULT 0 NOT NULL
);

CREATE TABLE APP_SCHEMA_VERSION (
    VERSION VARCHAR2(30) PRIMARY KEY,
    APPLIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

INSERT INTO APP_SCHEMA_VERSION (VERSION) VALUES ('2.1.0');
