-- Indices usados por filtros, agrupaciones y verificaciones.
CREATE INDEX IDX_TRANSACCIONES_FECHA ON TRANSACCIONES_PROCESADAS(FECHA);
CREATE INDEX IDX_TRANSACCIONES_ESTADO ON TRANSACCIONES_PROCESADAS(ESTADO);
CREATE INDEX IDX_INTERESES_ESTADO ON INTERESES_CALCULADOS(ESTADO);
CREATE INDEX IDX_MOVIMIENTOS_CUENTA ON MOVIMIENTOS_ANUALES(CUENTA_ID);
CREATE INDEX IDX_MOVIMIENTOS_FECHA ON MOVIMIENTOS_ANUALES(FECHA);
CREATE INDEX IDX_MOVIMIENTOS_ESTADO ON MOVIMIENTOS_ANUALES(ESTADO);
