SELECT * FROM APP_SCHEMA_VERSION ORDER BY APPLIED_AT DESC;

SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME LIKE 'BATCH_%'
   OR TABLE_NAME IN (
       'TRANSACCIONES_PROCESADAS', 'RESUMEN_TRANSACCIONES_DIARIAS',
       'INTERESES_CALCULADOS', 'MOVIMIENTOS_ANUALES', 'ESTADOS_CUENTA_ANUALES')
ORDER BY TABLE_NAME;

SELECT JOB_INSTANCE_ID, JOB_NAME FROM BATCH_JOB_INSTANCE ORDER BY JOB_INSTANCE_ID;
SELECT JOB_EXECUTION_ID, STATUS, START_TIME, END_TIME FROM BATCH_JOB_EXECUTION ORDER BY JOB_EXECUTION_ID;

SELECT COUNT(*) AS TRANSACCIONES FROM TRANSACCIONES_PROCESADAS;
SELECT COUNT(*) AS INTERESES FROM INTERESES_CALCULADOS;
SELECT COUNT(*) AS MOVIMIENTOS FROM MOVIMIENTOS_ANUALES;
SELECT * FROM RESUMEN_TRANSACCIONES_DIARIAS ORDER BY FECHA;
SELECT * FROM ESTADOS_CUENTA_ANUALES ORDER BY CUENTA_ID;
