spring.application.name=formativa1

# ==========================================
# ORACLE CLOUD
# ==========================================

spring.datasource.url=jdbc:oracle:thin:@plataformaatp_high?TNS_ADMIN=C:/oracle
spring.datasource.username=${ORACLE_DB_USERNAME}
spring.datasource.password=${ORACLE_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# ==========================================
# INICIALIZACION SQL
# ==========================================

# Para inicializar la base de datos con los scripts de schema y data al iniciar la aplicación (transacciones.csv,intereses.csv)
# spring.sql.init.mode=always
# para conservar los datos de la base de datos y no eliminar las tablas al iniciar la aplicación (cuentas_anuales.csv)
spring.sql.init.mode=never
spring.sql.init.platform=oracle
spring.sql.init.continue-on-error=true


# ==========================================
# ARCHIVOS CSV
# ==========================================

# 1 para usar con transaccionesJob
app.input-file=classpath:transacciones.csv

# 2 para usar con interesesJob
#app.input-file=classpath:intereses.csv

# 3 para usar con estadosCuentaJob
# app.input-file=classpath:cuentas_anuales.csv


# ==========================================
# SPRING BATCH
# ==========================================

spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.platform=oracle
spring.batch.jdbc.isolation-level-for-create=READ_COMMITTED

# Job que se ejecutará
# 1 para usar con transaccionesJob
spring.batch.job.name=transaccionesJob

# 2 para usar con interesesJob
# spring.batch.job.name=interesesJob

# 3 para usar con estadosCuentaJob
# spring.batch.job.name=estadosCuentaJob
