-- ADVERTENCIA: SCRIPT DESTRUCTIVO DE USO MANUAL.
-- Elimina datos de la aplicacion y su historial Batch. No se ejecuta automaticamente.
-- Requiere confirmacion explicita del responsable del esquema antes de usarlo.

DELETE FROM ESTADOS_CUENTA_ANUALES;
DELETE FROM MOVIMIENTOS_ANUALES;
DELETE FROM INTERESES_CALCULADOS;
DELETE FROM RESUMEN_TRANSACCIONES_DIARIAS;
DELETE FROM TRANSACCIONES_PROCESADAS;

DELETE FROM BATCH_STEP_EXECUTION_CONTEXT;
DELETE FROM BATCH_JOB_EXECUTION_CONTEXT;
DELETE FROM BATCH_STEP_EXECUTION;
DELETE FROM BATCH_JOB_EXECUTION_PARAMS;
DELETE FROM BATCH_JOB_EXECUTION;
DELETE FROM BATCH_JOB_INSTANCE;

COMMIT;
